Fix broken links to info on environment variables
folio-org/tech-council pull request #62
Opened 2024-02-22 13:54 UTC by maccabeelevine

I *believe* this is the correct destination page after the wiki migration, but @dltj could not confirm.

2024-03-05 18:42 UTC, craigmcnally submitted a review, later dismissed

2024-03-05 18:43 UTC, craigmcnally commented
I think this might be the page you're looking for:  https://folio-org.atlassian.net/wiki/spaces/TC/pages/5055298/DR-000020+-+Teams+must+document+deployment+requirements+in+a+clear+consistent+way

2024-03-05 18:46 UTC, craigmcnally commented on MODULE_ACCEPTANCE_CRITERIA.MD
> +  * -_note: read more at [https://folio-org.atlassian.net/wiki/spaces/SYSOPS/pages/2097733/Change+Environment+Variables+of+a+Module](https://folio-org.atlassian.net/wiki/spaces/SYSOPS/pages/2097733/C
See my comment about the correct(?) page.  Also, this notation is redundant if the link text and URL are identical

2024-12-18 16:04 UTC, todolson requested changes
Echoing @craigmcnally 's comment that [DR-000020 -Teams must document deployment requirements in a clear consistent way](https://folio-org.atlassian.net/wiki/spaces/TC/pages/5055298/DR-000020+-+Teams+must+document+deployment+requirements+in+a+clear+consistent+way) should be the correct link.

2025-01-20 09:02 UTC, inkuss approved these changes

2025-04-04 17:21 UTC, maccabeelevine commented
This is moot after #82 as Julian explains. https://github.com/folio-org/tech-council/pull/62#discussion_r1939317342

2025-04-04 17:21 UTC, closed without merging