Update workflow with DRAFT status
folio-org/tech-council pull request #7
Opened 2021-12-08 16:39 UTC by skoczko

2021-12-08 18:09 UTC, zburke requested changes
The only real request here is to correctly spell "submission" :) 

I personally like the phrase "resubmit" better than "resume", but I don't feel strongly about it.

2021-12-08 18:09 UTC, zburke commented on NEW_MOD_TECH_EVAL_JIRA.md
> +The submisison may be resumed at a later time.
I actually like the parity of "resubmitted" with the state "submitted". "Resumed" to me implies the process was paused in the middle, not that it entered a "final" state (such as "Cancelled" or "Rejected").

2021-12-08 18:09 UTC, zburke commented on NEW_MOD_TECH_EVAL_JIRA.md
> +The submitter may resume the submission once the failed criteria are addressed.
As above, I actually like "resubmit".

2022-01-06 21:52 UTC, craigmcnally commented on NEW_MOD_TECH_EVAL_JIRA.md
>  **UNDER EVALUATION** Once the sumbmission is reviewed by the TC and an evaluation group is formed, the TC indicates this by transitioning the issue to this state.
```suggestion
**UNDER EVALUATION** Once the submission is reviewed by the TC and an evaluation group is formed, the TC indicates this by transitioning the issue to this state.
```

2022-02-11 19:57 UTC, jeremythuff approved these changes

2022-02-11 20:08 UTC, craigmcnally approved these changes

2022-02-11 20:08 UTC, merged