Merge eval form into eval criteria
folio-org/tech-council pull request #86
Opened 2024-12-09 13:15 UTC by julianladisch

* Avoid two documents with almost the same content.
* Avoid that the two documents get out of sync.
* Ensure that the references to the "Values", like `(6)`, are in the evaluation form, and can be found in both raw and rendered form.

2024-12-16 14:43 UTC, maccabeelevine requested changes
Minor suggestion below, otherwise looks good

2024-12-16 14:43 UTC, maccabeelevine commented on MODULE_ACCEPTANCE_CRITERIA.MD
> +16. Modules conforms to FOLIO upgrade mechanisms
Better to leave these all as `1.` so it's easier to add/remove as needed without changing every other line?

2024-12-16 15:05 UTC, todolson approved these changes
Agreed that this is a significant improvement. I don't have a strong view about the numbering under Values. Numbers make it easier to reference, but I take the point about renumbering. That said, I don't think this lists changes frequently.

2024-12-16 15:27 UTC, kaladay requested changes

2024-12-16 15:27 UTC, kaladay commented on MODULE_ACCEPTANCE_CRITERIA.MD
> +Remove the Frontend or the Backend section.
```suggestion
Remove either the Frontend or the Backend section.
```
I think adding `either` here makes more sense.

2024-12-16 16:20 UTC, maccabeelevine approved these changes

2024-12-16 16:20 UTC, maccabeelevine commented on MODULE_ACCEPTANCE_CRITERIA.MD
> +16. Modules conforms to FOLIO upgrade mechanisms
That's fair.

2024-12-18 14:24 UTC, kaladay approved these changes

2025-01-29 16:49 UTC, craigmcnally commented
This PR should be merged last, after the other various PRs we're planning to merge.

2025-02-03 12:25 UTC, merged